src/AuShadha/AuShadha/urls.py
from __future__ import absolute_import
from __future__ import print_function
from django.conf.urls import url , include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views 

from AuShadha import settings
from aushadha_users.views import login_view, logout_view


from .startup import run

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^AuShadha/search/', include('search.urls') ),

    url(r'^home/', include('aushadha_ui.urls') ),
    url(r'^AuShadha/home/', include('aushadha_ui.urls') ),
    url(r'^AuShadha/ui/', include('aushadha_ui.urls') ),
    # url(r'^$', include('aushadha_ui.urls'))

    url(r'^AuShadha/authenticate/', include('aushadha_users.urls')),

    #    url(r'^AuShadha/logout/$', include('aushadha_users.urls')),


  url(r'^AuShadha/icd10/'  , include('registry.icd10.urls') ),
  url(r'^AuShadha/icd10pcs/' , include('registry.icd10pcs.urls') ),
  url(r'^AuShadha/drug_db/'  , include('registry.drug_db.urls') ),
  url(r'^AuShadha/fda_drug_db/', include('registry.drug_db.urls') ),
  url(r'^AuShadha/drugbankcadrugs/', include('registry.drug_db.drugbankca.urls') ),


  url(r'^AuShadha/pat/'    , include('patient.urls') ),
  url(r'^AuShadha/patient/', include('patient.urls') ),
  url(r'^AuShadha/patient/', include('patient.urls') ),

# url(r'^AuShadha/admission/', include('admission.admission.urls') ),
# url(r'^AuShadha/demographics/', include('demographics.demographics.urls') ),
# url(r'^AuShadha/contact/'     , include('demographics.contact.urls') ),
# url(r'^AuShadha/phone/'       , include('demographics.phone.urls') ),
# url(r'^AuShadha/guardian/'    , include('demographics.guardian.urls') ),
# url(r'^AuShadha/email_and_fax/',include('demographics.email_and_fax.urls') ),
# url(r'^AuShadha/family_history/'  , include('history.family_history.urls')),
# url(r'^AuShadha/social_history/'  , include('history.social_history.urls')),
# url(r'^AuShadha/medical_history/' , include('history.medical_history.urls')),
# url(r'^AuShadha/surgical_history/', include('history.surgical_history.urls')),
# url(r'^AuShadha/obs_and_gyn/'    , include('history.obs_and_gyn.urls') ),
# url(r'^AuShadha/medication_list/', include('medication_list.urls') ),
# url(r'^AuShadha/allergy_list/'   , include('allergy_list.urls') ),
# url(r'^AuShadha/immunisation/'   , include('immunisation.urls') ),

# url(r'^AuShadha/visit/'             , include('visit.visit.urls')),
# url(r'^AuShadha/visit_complaint/'   , include('visit.visit_complaints.urls') ),
# url(r'^AuShadha/visit_complaints/'  , include('visit.visit_complaints.urls') ),
# url(r'^AuShadha/visit_hpi/'         , include('visit.visit_hpi.urls') ),
# url(r'^AuShadha/visit_ros/'         , include('visit.visit_ros.urls') ),
# url(r'^AuShadha/visit_phyexam/'     , include('visit.visit_phyexam.urls') ),
# url(r'^AuShadha/visit_assessment_and_plan/',include('visit.visit_assessment_and_plan.urls') ),
# url(r'^AuShadha/visit_soap/' , include('visit.visit_soap.urls') ),
# url(r'^AuShadha/visit_prescription/',include('visit.visit_prescription.urls') ),

# url(r'^AuShadha/follow_up/', include('visit.urls')),
# url(r'^AuShadha/phyexam/'  , include('phyexam.urls')),

# Admin and Admin Docs URL:
#   url(r'^AuShadha/admin/', include(admin.site.urls)),
#   url(r'^AuShadha/admin/doc/', include('django.contrib.admindocs.urls')),

# Media URL
# url( r'^AuShadha/media/(?P<path>.*)$', 
#        'django.views.static.serve',
#        {'document_root': settings.MEDIA_ROOT}, 
#        'show_indexes:True'
#        ),

# Home URL
# TODO This will be the true address.. a kind of like a Dashboard. 
#      Till then use the one below for /AuShadha/home/
#(r'^AuShadha/home/$', 'home.views.home'),
#(r'^AuShadha/home/$', 'patient.views.patient_list'),

# Login and Logout URLS
    #url(r'^AuShadha/log/', include('aushadha_users.urls') ),
    #url(r'^AuShadha/logout/$',include('aushadha_users.urls') ),
    url(r'^AuShadha/authenticate/', include('aushadha_users.urls') ),

#url(r'^AuShadha/login/$', login_view, name="login"),
#url(r'^AuShadha/logout/$',logout_view, name="logout"),

# If it dosent match anything else..
#(r'^AuShadha/alternate_layout/$','patient.views.alternate_layout'),
#(r'^AuShadha/$', 'patient.views.patient_list'),
#(r'^$', 'patient.views.patient_list'),
# url(r'^AuShadha/', include('aushadha_ui.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG == True:
    urlpatterns += staticfiles_urlpatterns()

#print(urlpatterns)




# Right now Django does not allow custom statup code to run anywhere 
# So if we want to run code after AppRgistry.ready<Bool> this is the safe
# place 
run() 

src/AuShadha/patient/urls.py
from django.conf.urls import *
from django.contrib import admin
import AuShadha.settings

from .views import *
from .dijit_widgets.pane import render_patient_pane
from .dijit_widgets.tree import render_patient_tree

admin.autodiscover()

urlpatterns = [ 

################################ PATIENT CRUD ##################################

   url(r'new/add/(?P<clinic_id>\d+)/$'                             ,
       patient_detail_add,
       name='patient_detail_add'
       ),

   url(r'new/add/$'                             ,
       patient_detail_add,
       name='patient_detail_add_without_id'
       ),

   url(r'patient/edit/(?P<id>\d+)/$',
       patient_detail_edit,
       name='patient_detail_edit'
       ),

   url(r'patient/del/(?P<id>\d+)/$',
       patient_detail_del,
       name='patient_detail_del'
       ),


################################ PATIENT JSON ##################################

   url(r'patient/json/$',
           render_patient_json,
           name='render_patient_json'
       ),


################################ PATIENT SUMMARY ###############################

   url(r'patient/summary/$',
       render_patient_summary,
       name='render_patient_summary_without_id'
       ),

   url(r'patient/summary/(?P<patient_id>\d+)/$',
       render_patient_summary,
       name='render_patient_summary_with_id'
       ),

################################ PATIENT INFO  #################################

  url(r'patient/info/(?P<patient_id>\d+)/$',
       render_patient_info,
       name='render_patient_info'
       ),

################################ PATIENT PANE ##################################

  url(r'patient/pane/(?P<patient_id>\d+)/$',
       render_patient_pane,
       name='render_patient_pane_with_id'
       ),

  url(r'patient/pane/$',
       render_patient_pane,
       name='render_patient_pane_without_id'
       ),

################################ PATIENT TREE ##################################

   url(r'patient/tree/(?P<patient_id>\d+)/$',
       render_patient_tree,
       name='render_patient_tree_with_id'
       ),

   url(r'patient/tree/$',
       render_patient_tree,
       name='render_patient_tree_without_id'
       ),

############################ PATIENT INDEX ######################################

   #url(r'patient/index/$',
       #'patient.views.patient_index',
       #name='patient_index'
       #),

############################ PATIENT LIST ######################################

   #url(r'patient/list/$',
       #'patient.views.render_patient_list' ,
       #name='render_patient_list'
       #),

   #    url(r'patient/list/(?P<id>\d+)/$',
   #            'patient.views.patient_detail_list',
   #            name = 'patient_detail_list'
   #    ),

]

src/AuShadha/search/urls.py
from __future__ import absolute_import
from django.conf.urls import url , include
#from django.views.generic.simple import direct_to_template

import AuShadha.settings

from .views import aushadha_patient_search
from .dijit_widgets.pane import render_aushadha_search_pane, render_aushadha_search_form

urlpatterns = [
  url(r'patient/$',
      aushadha_patient_search, 
      name='aushadha_patient_search' 
  ),
  url(r'patient/(?P<patient_id>\d+)/$',
      aushadha_patient_search,
      name='aushadha_patient_search_with_id'
  ),
  url(r'pane/$',
      render_aushadha_search_pane,
      name='render_aushadha_search_pane'
  ),
  url(r'render/form/$',
      render_aushadha_search_form,
      name='render_aushadha_search_form'
  ),
] 

src/AuShadha/patient/models.py
################################################################################
# PROJECT      : AuShadha2.0
# Description  : Patient Models for managing patient
# Author       : Dr. Easwar T R
# Date         : 04-12-2016
# Licence      : GNU GPL V3. Please see AuShadha/LICENSE.txt
################################################################################


from __future__ import absolute_import
from __future__ import print_function
from django.db import models
from django.contrib.auth.models import User
import six

# AuShadha Imports
from aushadha_users.models import AuShadhaUser
from aushadha_base_models.models import AuShadhaBaseModel, \
                                        AuShadhaBaseModelForm
from clinic.models import Clinic

from .dijit_fields_constants import PATIENT_DETAIL_FORM_CONSTANTS
from AuShadha.settings import APP_ROOT_URL

DEFAULT_PATIENT_DETAIL_FORM_EXCLUDES=('parent_clinic',)

class PatientDetail(AuShadhaBaseModel):

    """
      Patient Model definition for Registration, 
      Name entry and Hospital ID Generation
    """

   # Some data to Generate the URLS

    def __init__(self,*args,**kwargs):
      super(PatientDetail,self).__init__(*args, **kwargs)
      self.__model_label__ = "patient"
      self._parent_model = 'parent_clinic'


    # Model attributes
    patient_hospital_id = models.CharField('Hospital ID',
                                            max_length=15,
                                           unique=True)
    first_name = models.CharField(max_length=30)
    middle_name = models.CharField(max_length=30,
                                   help_text="Please enter Initials / Middle Name", blank=True,
                                   null=True)
    last_name = models.CharField(max_length=30,
                                 blank=True,
                                 null=True,
                                 help_text="Enter Initials / Last Name"
                                 )
    full_name = models.CharField(max_length=100,
                                 editable=False,
                                 null=False,
                                 blank=False
                                 )
    age = models.CharField(max_length=10, blank=True, null=True)
    sex = models.CharField(max_length=6,
                           choices=(("Male", "Male"),
                                    ("Female", "Female"),
                                    ("Others", "Others")
                                    ),
                           default = "Male")
    parent_clinic = models.ForeignKey(Clinic, on_delete = models.CASCADE )



    class Meta:
        verbose_name = "Patient - Basic Data"
        verbose_name_plural = "Patient - Basic Data"
        ordering = ('first_name',
                    'middle_name',
                    'last_name',
                    'age', 'sex',
                    'patient_hospital_id'
                    )
        unique_together = ('patient_hospital_id', 'parent_clinic')


    def get_all_json_exportable_fields(self):
      """
        Gets the JSON exportable fields and its values as key, value pair
        This skips AutoField, OneToOneField type of field
      """
      exportable_fields = {}
      for item in self._meta.get_fields_with_model():
        if item[0].__class__.__name__ not in ['OneToOneField']:
          exportable_fields[item[0][0].name] = item[0][0].value_from_object(self)
        else:
          continue
      return exportable_fields


    def __unicode__(self):
        if self.middle_name and self.last_name:
            return "%s %s %s" % (self.first_name.capitalize(),
                                 self.middle_name.capitalize(),
                                 self.last_name.capitalize()
                                 )
        elif self.last_name or self.middle_name:
          if self.last_name:
            return "%s %s" % (self.first_name.capitalize(),
                               self.last_name.capitalize())
          else:
            return "%s %s" % (self.first_name.capitalize(),
                              self.middle_name.capitalize())


    def check_before_you_add(self):
      """
        Checks whether the patient has already been registered in the
        database before adding.
      """
      all_pat = PatientDetail.objects.all()
      hosp_id = self.patient_hospital_id
      id_list = []
      if all_pat:
        for p in all_pat:
            id_list.append(p.patient_hospital_id)
        if hosp_id in id_list:
            error = "Patient is already registered"
            print(error)
            return False
        else:
            return True
      else:
          return True

    def save(self, *args, **kwargs):

        """
          Custom Save Method needs to be defined.
          This should check for:
          1. Whether the patient is registered before.
          2. Patient DOB / Age Verfication and attribute setting
          3. Setting the full_name attribute
        """

        self.check_before_you_add()
        self._set_full_name()
    #     self._set_age()
        super(PatientDetail, self).save(*args, **kwargs)


    def _field_list(self):
        self.field_list = []
        print(self._meta.fields)
        for field in self._meta.fields:
            self.field_list.append(field)
        return self.field_list

    def _formatted_obj_data(self):
        if not self.field_list:
            _field_list()
        str_obj = "<ul>"
        for obj in self._field_list:
            _str += "<li>" + obj + "<li>"
            str_obj += _str
        str_obj += "</ul>"
        return str_obj


    def _set_full_name(self):

        """
            Defines and sets the Full Name for a Model on save.
            This stores the value under the self.full_name attribute.
            This is mainly intented for name display and search
        """

        if self.middle_name and self.last_name:
            self.full_name = six.text_type(self.first_name.capitalize() + " " +
                                     self.middle_name.capitalize() + " " +
                                     self.last_name.capitalize()
                                     )
        else:
          if self.last_name:
            self.full_name = six.text_type(self.first_name.capitalize() + " " +
                                     self.last_name.capitalize()
                                     )
          if self.middle_name:
            self.full_name = six.text_type(self.first_name.capitalize() + " " +
                                     self.middle_name.capitalize()
                                     )
        return self.full_name


    def _set_age(self):

        """ Check DOB and Age. See Which one to set.
            Dont set age if DOB is given.
            Dont allow age > 120 to be set.
            This should be called before Form & Model save.
            If this returns false, the save should fail raising proper Exception
        """

        if self.date_of_birth:
            min_allowed_dob = datetime.datetime(1900, 0o1, 0o1)
            max_allowed_dob = datetime.datetime.now()
            if self.date_of_birth >= min_allowed_dob and \
                self.date_of_birth <= max_allowed_dob:
                self.age = "%.2f" % (
                    round((max_allowed_dob - self.date_of_birth).days / 365.0, 2))
                return True
            else:
                raise Exception(
                    "Invalid Date: Date should be from January 01 1900 to Today's Date")
        else:
            if self.age and int(self.age[0:3]) <= 120:
                self.date_of_bith = None
                return True
            else:
                raise Exception("Invalid Date of Birth / Age Supplied")
                return False




class PatientDetailForm(AuShadhaBaseModelForm):

    """
        ModelForm for Patient Basic Data
    """

    __form_name__ = "Patient Detail Form"

    dijit_fields = PATIENT_DETAIL_FORM_CONSTANTS

    class Meta:
        model = PatientDetail
        exclude = DEFAULT_PATIENT_DETAIL_FORM_EXCLUDES

src/AuShadha/patient/templates/patient_detail/add.html
{% if perms.patient.add_patientdetail %}

<div data-dojo-type = "dijit/form/Form" 
     id             = "newPatientAddForm" 
     data-dojo-id   = "newPatientAddForm"
     encType        = "multipart/form-data" 
     action         = "" 
     method         = "">

    <script type="dojo/method" data-dojo-event="onReset">
        return true;
    </script>

    <script type="dojo/method" data-dojo-event="onSubmit">
     if(this.validate()){
      require(["dojo/_base/xhr", 
               "dojo/dom", 
               "dojo/json", 
               "dijit/registry", 
               "dijit/Dialog",
               "dojo/domReady!"
      ],
      function(xhr, dom, JSON, registry, Dialog){
            var editDialog = registry.byId("editPatientDialog");
            var errorDialog = registry.byId("dialogJsonMessage");

//{% if perms.patient.add_patientdetail %}
        xhr.post({
                url  : "{%url 'patient_detail_add_without_id' %}",
                form : dom.byId("newPatientAddForm"),
                load : function(json) {
                        var jsondata = JSON.parse(json);
                        if(jsondata.success == true){
                            dom.byId("newPatientAddForm").reset();
//                             var data = jsondata.addData;
//                             grid.store.newItem(data);
                            publishInfo("<p class='suggestion_text'>New Patient Added Successfully.<p>\
                                          \nPlease switch Search Tab if you want to open Chart"
                            );
                            if(ADD_MORE_PATIENTS == false){
                              editDialog.hide();
                            }
                            else{
                              registry.byId("id_patient_hospital_id").focus();
                            }
                        }
                        else{
                            var content = jsondata.error_message + "\n" + jsondata.form_errors;
                            publishError(content );
                        }
                },
                error: function(json) {
                          var jsondata = JSON.parse(json)
                          publishError("ERROR! : \n"+ jsondata.error_message);
                }
        });

//	{% else %}
    registry.byId("permissionDeniedErrorDialog").show();
    return false;

//  {% endif %}
    });
    return false;
    }
    else{
     registry.byId("invalidFormSubmissionErrorDialog").show();
     return false;
    }

  </script>

  {% if perms.patient.add_patientdetail %}
		<table id		=	"patient_detail_add_form_table"> 
					{{patient_detail_form}} 
		</table>

     <button data-dojo-type = "dijit/form/Button" 
            data-dojo-props="iconClass: 'dijitIconSave'"
            type           = "submit" 
            name           = "submitButton" 
            value          = "Add">
        Save
       <script type            = "dojo/connect" 
               data-dojo-event = "onClick" 
               data-dojo-args  = "evt"
       >
         ADD_MORE_PATIENTS = false;
         ADD_MORE_ITEMS    = false;
       </script>
     </button>


    <button data-dojo-type = "dijit/form/Button" 
            type           = "submit" 
            name           = "submit_and_add_more_patients" 
            value          = "Add &amp; More"
            data-dojo-props="iconClass: 'dijitIconSave'"
            >
       Save & Add More
       <script type            = "dojo/connect" 
               data-dojo-event = "onClick" 
               data-dojo-args  = "evt"
       >
         ADD_MORE_PATIENTS = true;
         ADD_MORE_ITEMS    = true;
       </script>
     </button>


    <button data-dojo-type  = "dijit/form/Button" 
            data-dojo-props="iconClass: 'dijitIconClear'"
            type            = "reset">
       Reset
    </button>
  {% endif %}

</div>
{% else %}
<p class="suggestion_text"> Insufficient Permissions</p>
{% endif %} 

src/AuShadha/patient/templates/patient_detail/edit.html
{% if user and user.is_authenticated %}

<div data-dojo-type = "dijit/form/Form" 
     id             = "newPatientEditForm" 
     data-dojo-id   = "newPatientEditForm"
     encType        = "multipart/form-data" 
     action 	    =  "" 
     method         =  ""
   >


      <script type="dojo/method" data-dojo-event="onSubmit">

      if( this.validate() ){

        require(

          ["dojo/_base/xhr", 
            "dojo/dom", 
            "dojo/dom-attr",
            "dojo/json", 
            "dojo/_base/fx",
            "dijit/Dialog",
            "dijit/form/Form",
            "dijit/form/Button",
            "dijit/form/ValidationTextBox", 
            "dijit/form/Select",
            "dijit/registry",
            "dojo/query",
            "dojo/NodeList-traverse",
            "dojo/NodeList-data"
          ],

        function(xhr, dom, domAttr, JSON,
                 fx, Dialog, Form, 
                 Button, TextBox, 
                 Select, registry, query){

        // {% if perms.patient.change_patientdetail %}

            xhr.post({

                    url  : "{{patient_detail_obj.urls.edit}}",

                    form : dom.byId("newPatientEditForm"),

                    load : function(json) {

                            var jsondata = JSON.parse(json)

                            var allTopPanes = query(".topContentPane.selected");

                            if ( jsondata.success == true ) {

                                allTopPanes.forEach(

                                  function ( node ) {
                                    var domId  = domAttr.get( node, 'id' );
                                    var widget = registry.byId( domId );
                                    widget.set( 'href', "{{patient_detail_obj.urls.info}}" );
                                  }

                                );

                                registry.byId("PATIENT").set('href', "{{patient_detail_obj.urls.pane}}" );

                                publishInfo(jsondata.error_message);
                                registry.byId("editPatientDialog").hide();

                            }
                            else{
                                publishError(jsondata.error_message);
                            }
                    },
                    error: function(response) {
                                publishError(response);
                    }
            });

          //{% else %}

            registry.byId("permissionDeniedErrorDialog").show();

          //{%endif %}

      });

      return false;

      }

      else{

      registry.byId("invalidFormSubmissionErrorDialog").show();
      return false;

      }

    </script>

    <table id		=	"patient_detail_edit_form_table"> 
                {{patient_detail_edit_form}} 
    </table>

    {% if perms.patient.change_patientdetail %}

      <button data-dojo-type = "dijit/form/Button" 
            data-dojo-props="iconClass: 'dijitEditorIcon dijitEditorIconSave'"
            type           = "submit" 
            name           = "editButton" 
            value          = "Edit">
      Edit
     </button>

    {%endif%}


    {% if perms.patient.delete_patientdetail %}

    <button data-dojo-type  = "dijit/form/Button" 
						data-dojo-props="iconClass: 'dijitEditorIcon dijitEditorIconDelete'"    
            type            = "button"
            name            = "delPatient"
            id              = "delPatientBtn">
       Delete

   <script type="dojo/method" data-dojo-event="onClick" data-dojo-args="evt">

			  require(

			    ["dojo/dom", 
			     "dojo/_base/xhr",
			     "dojo/json",
			     "dijit/registry",
			     "dijit/Dialog"
			    ],

			  function(dom, xhr, JSON, registry, Dialog){

					var _c  = confirm("This will Delete the Patient and all related Data. Proceed ? " );

					if ( _c ) {

                        xhr.get({

                          url: "{{patient_detail_obj.urls.del}}",

                          load: function(json){

                                  var jsondata = JSON.parse(json)

                                  if (jsondata.success == true){

                                      var cTopTabPane = registry.byId("centerTopTabPane")
                                      var children = cTopTabPane.getChildren();

                                      children.forEach(

                                        function ( tab ) {
                                          if ( children.indexOf(tab) > 0 ){
                                              cTopTabPane.removeChild(tab);
                                              tab.destroyRecursive();
                                          }
                                        }

                                      );

                                      registry.byId("editPatientDialog").hide();
                                      publishInfo(jsondata.error_message);

                                  }

                                  else{
                                      publishError(jsondata.error_message);
                                  }

                                }

                        });
                  }

                  else {

                    registry.byId("editPatientDialog").hide();                  
                    return false;

                  }

			  });
    </script>

    </button>

  {% endif %}


</div>

{% else %}

<p class="suggestion_text"> Please Login </p>

{% endif %}

src/AuShadha/patient/templates/patient_detail/info.html
{{info.full_name}} - {{info.age}} - ({{info.patient_hospital_id}})